### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by Andarist** [Andarist/babel-plugin-annotate-pure-calls#2]
@kzc

> As for babel-plugin-annotate-pure-calls perhaps you could add some more documentation to its README explaining the use cases where it should and should not be used.

Already added some more documentation, but I certainly intend to work on that more soon.

> The case result I cited was quite unexpected to me. I'm not convinced your revised example would be problem-free either.

Could you describe why the revised example might not be problem-free?

> Perhaps this Babel plugin can only be used on pure functional libraries were every single function (internal or external) is known to be pure beforehand?

That is certainly the safest use case for this plugin, but I believe that's not the only one. I think that even effectful (in assignment contexts) calls can be annotated quite safely, if the result is not used by the program there is really high chance that side-effects of the call itself are also not relevant. This is an assumption ofc, but I think if in such example:

```js
var unused = sideEffects()
```

those side effects are still needed for the program it is a sign that its weirdly/poorly structured program and should be restructured. 

I wouldnt be too cautious before running this plugin (assuming the plugin working as expected) even on my applications' code (and im not hardcore fp purist). Ofc results need to be always verified and tested.

**Comment by kzc** [comment]
Maybe I'm not understanding the use case for this plugin correctly.

What would you want this plugin to produce for the following code:
```
$ cat example.js 
function call(x) {
    var result = `(call ${x})`;
    return console.log(result), result;
}
function someOtherCall(x) {
    var result = `(someOtherCall ${x})`;
    return console.log(result), result;
}
a = (function() {
  var b = (function() {
    var c = (function() {
      var d = call(123);
      return someOtherCall(d);
    })()
  })()
})();
```
```
$ node example.js 
(call 123)
(someOtherCall (call 123))
```
given that uglify would `compress` the code to:
```
$ bin/uglifyjs example.js -c -b
function call(x) {
    var result = `(call ${x})`;
    return console.log(result), result;
}

function someOtherCall(x) {
    var result = `(someOtherCall ${x})`;
    return console.log(result), result;
}

a = void someOtherCall(call(123));
```

**Comment by kzc** [comment]
I meant to write this code:
```
$ cat example2.js 
function call(x) {
    var result = `(call ${x})`;
    return console.log(result), result;
}
function someOtherCall(x) {
    var result = `(someOtherCall ${x})`;
    return console.log(result), result;
}
a = (function() {
  var b = (function() {
    var c = (function() {
      var d = call(123);
      return someOtherCall(d);
    })();
    return c;
  })();
  return b;
})();
```
```
$ bin/uglifyjs example2.js -c -b
function call(x) {
    var result = `(call ${x})`;
    return console.log(result), result;
}

function someOtherCall(x) {
    var result = `(someOtherCall ${x})`;
    return console.log(result), result;
}

a = someOtherCall(call(123));
```
No matter - what result would you want for both programs?

**Comment by Andarist** [comment]
When those calls would get annotated (after a pass through this plugin). I would expect exactly what you have described

For `example.js` it would drop the calls entirely - producing `a = void 0` or something. As results of those calls are not used by the program.

For `example2.js` it would just unwind the IIFEs and produce `a = someOtherCall(call(123));` as shown.

All this lives ofc under the assumption that functions are pure if called in assignment context and even if they produce some side-effects, those become irrelevant if the result is unused.

As to annotating automatically within "top-level IIFEs" I will certainly provide a configurable option for this, just aint sure what default behaviour I should chose. I'm leaning towards the current though.
